version: '3.8'

services:
  binance-mcp: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binance-mcp-server
    environment:
    #  - BINANCE_API_KEY=${BINANCE_API_KEY}
    #  - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - BINANCE_TESTNET=true
    stdin_open: true
    tty: true
    # ports:
    #   - "3000:3000"
    # restart: unless-stopped
